[project]
name = "aka-foil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tjalf Stadel", email = "tjalf.stadel@web.de" },
    { name = "Jannik Frank", email = "jannik.frank@akamodell.de"}
]
requires-python = ">=3.12"
dependencies = [
    "keras>=3.8.0",
    "numpy>=2.0.2",
    "polars>=1.19.0",
    "ray[tune]>=2.40.0",
    "torch>=2.5.1",
]

[project.scripts]
aka-foil = "aka_foil:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
